### ISSUE TITLE
remove blue background from SlidingUpPanelWidget

### ISSUE THREAD

**Issue by wesleytoshio** [JackJonson/flutter_sliding_up_panel#1]
### need this for possible rounded border
![image](https://user-images.githubusercontent.com/7057737/77011510-cc0b2400-694a-11ea-923b-0f18c9e29eee.png)

**Comment by JackJonson** [comment]
It has been resolved in version 1.0.0, you can try it.

**Comment by JackJonson** [comment]
> ### need this for possible rounded border
> ![image](https://user-images.githubusercontent.com/7057737/77011510-cc0b2400-694a-11ea-923b-0f18c9e29eee.png)

It has been resolved in version 1.0.0, you can try it.
