### ISSUE TITLE
Feature : disable onTap detection

### ISSUE THREAD

**Issue by QuentinSc** [JackJonson/flutter_sliding_up_panel#4]
Hello,

Very good work and the simplest to use !
Can you add a boolean to choose if we want to use or not the onTap ? 

` onTap: () {
        if (SlidingUpPanelStatus.anchored == widget.panelController.status) {
          collapse();
        } else if (SlidingUpPanelStatus.collapsed ==
            widget.panelController.status) {
          anchor();
        } else if (SlidingUpPanelStatus.expanded ==
            widget.panelController.status) {
          collapse();
        } else {
          collapse();
        }
      },`

**Comment by JackJonson** [comment]
Upgrade to  1.1.0  should solve it.
